### ISSUE TITLE
UnicodeEncodeError in csv.py

### ISSUE THREAD

**Issue by rupertlevene** [awdeorio/mailmerge#17]
In python 2.7, the csv module doesn't like non-ascii characters. Can mailmerge work around this? Maybe https://github.com/jdunck/python-unicodecsv is an option?

```
$ mailmerge --sample; sed -ie 's/Myself/étoile/' mailmerge_database.csv; mailmerge
Creating sample template email mailmerge_template.txt
Creating sample database mailmerge_database.csv
Creating sample config file mailmerge_server.conf
Edit these files, and then run mailmerge again
Traceback (most recent call last):
  File "/usr/local/bin/mailmerge", line 9, in <module>
    load_entry_point('mailmerge==1.7.2', 'console_scripts', 'mailmerge')()
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build/bdist.macosx-10.11-intel/egg/mailmerge/main.py", line 213, in main
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/csv.py", line 108, in next
    row = self.reader.next()
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 21: ordinal not in range(128)
```

**Comment by awdeorio** [comment]
I added a branch and unit test for this issue https://github.com/awdeorio/mailmerge/tree/bugfix/utf8-database

I'll give the backport a try.

**Comment by awdeorio** [comment]
And it works!
