### ISSUE TITLE
AttributeError: 'list' object has no attribute 'decode'

### ISSUE THREAD

**Issue by mkitzmann** [awdeorio/mailmerge#30]
Great tool! Does exactly what I am looking for.
There is just one Issue when trying to send a multipart message, I am getting this error:

```python
mailmerge --dry-run
>>> message 0
TO: myself@mydomain.com
SUBJECT: Testing mailmerge
FROM: My Self <myself@mydomain.com>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="outer-boundary"

This is a MIME-encoded message. If you are seeing this, your mail
reader is old.

--outer-boundary
Content-Type: text/plain; charset=us-ascii

Hi, Myself,

Your number is 17.

Sent by mailmerge https://github.com/awdeorio/mailmerge

--outer-boundary
MIME-Version: 1.0
Content-Type: multipart/related;
  type="text/html"; start="<body@here>"; boundary="inner-boundary"

--inner-boundary
Content-Type: text/html; charset=us-ascii
Content-Disposition: inline
Content-ID: <body@here>

<html>
<body>

<p>Hi, Myself,</p>

<p>Your number is 17.</p>

<p>Sent by <a href="https://github.com/awdeorio/mailmerge">mailmerge</a></p>

</body>
</html>
Traceback (most recent call last):
  File "/usr/local/bin/mailmerge", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mailmerge/__main__.py", line 45, in cli
    config_filename=config_filename,
  File "/usr/local/lib/python2.7/site-packages/mailmerge/api.py", line 238, in main
    (text, sender, recipients) = parsemail(raw_message)
  File "/usr/local/lib/python2.7/site-packages/mailmerge/api.py", line 39, in parsemail
    message.set_charset(encoding)
  File "/usr/local/lib/python2.7/site-packages/future/backports/email/message.py", line 320, in set_charset
    cte(self)
  File "/usr/local/lib/python2.7/site-packages/future/backports/email/encoders.py", line 68, in encode_7or8bit
    orig.decode('ascii')
AttributeError: 'list' object has no attribute 'decode'
```

I have used the --sample flag and copied the multipart example in the Readme.
Working with plain text and pure html emails works.

Any Idea, what this could be? I would be more than happy to help if possible.

**Comment by awdeorio** [comment]
Hmm, it looks like this is an interaction between setting the content encoding and multipart messages.  Try this idea in branch `bugfix/30-multipart-encoding`.  If it tests out, I'll merge into master.

**Comment by mkitzmann** [comment]
It works fine! Thank you.
