### ISSUE TITLE
Unicode support in message header

### ISSUE THREAD

**Issue by awdeorio** [awdeorio/mailmerge#49]
Add and verify unicode support in message header, including subject, sender name, and recipient name.

https://en.wikipedia.org/wiki/Unicode_and_email#Unicode_support_in_message_header

EDIT: it's possible that this already works.  Add tests:
- Test UTF8 in subject
- Test UTF8 in sender name
- Test UTF8 in recipient name
- Test end-to-end with all of the above and verify stdout

**Comment by awdeorio** [comment]
I've run into a known issue on Python 2 with UTF-8 in the sender's name.

`mailmerge_template.txt`
```
TO: Laȝamon <to@test.com>
FROM: from@test.com

Hello world
```

`mailmerge_database.csv` is just a dummy row to ensure that one message is rendered.
```
placeholder
value
```

`mailmerge_server.conf` is a simple open server config.
```
[smtp_server]
host = open-smtp.example.com
port = 25
```

Run with Python 2
```console
$ which mailmerge
/Users/awdeorio/src/mailmerge/env2/bin/mailmerge
(env2) feature/54-tests* env2 awdeorio@manzana tmp
$ which python
/Users/awdeorio/src/mailmerge/env2/bin/python
(env2) feature/54-tests* env2 awdeorio@manzana tmp
$ python --version
Python 2.7.17
$ mailmerge
>>> message 0
Traceback (most recent call last):
  File "/Users/awdeorio/src/mailmerge/env2/bin/mailmerge", line 11, in <module>
    load_entry_point('mailmerge', 'console_scripts', 'mailmerge')()
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/awdeorio/src/mailmerge/mailmerge/__main__.py", line 99, in cli
    print(message.as_string())
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/message.py", line 155, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/generator.py", line 118, in flatten
    self._write(msg)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/generator.py", line 190, in _write
    self._write_headers(msg)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/generator.py", line 217, in _write_headers
    self.write(self.policy.fold(h, v))
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/_policybase.py", line 321, in fold
    return self._fold(name, value, sanitize=True)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/_policybase.py", line 360, in _fold
    maxlinelen=self.max_line_length))
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/header.py", line 375, in encode
    formatter.feed('', lines[0], charset)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/header.py", line 462, in feed
    encoded_lines = charset.header_encode_lines(string, self._maxlengths())
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/charset.py", line 362, in header_encode_lines
    lines.append(encoder(header_bytes))
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/backports/email/base64mime.py", line 73, in header_encode
    header_bytes = header_bytes.encode(charset)
  File "/Users/awdeorio/src/mailmerge/env2/lib/python2.7/site-packages/future/types/newbytes.py", line 410, in __getattribute__
    raise AttributeError("encode method has been disabled in newbytes")
AttributeError: encode method has been disabled in newbytes
```
